# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bef8e11e8f95b95aeebe4b8256004b4b14e07d8e0bb8040cc9372af8a805031537ea7957be20e7276f63a16fa03cc2de283b9f0eebd52cb4f6e349509dd38eca

test:
  secret_key_base: 43414000d45b42b5ffb52e1cbbf521ae5997d56a2af604fef87b42ef99a829877086df1978bbefc41ac0731426965131569ef173a67fae4f686d13a9d52e2c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
